package xy.media.oneplayer.data.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BASE_FILE".
 */
public class BaseFile {

    private Long id;
    private String path;
    private String type;
    private String name;
    private Boolean selected;
    private Boolean isdirectory;
    private String size;
    private java.util.Date time;
    private String parent_folder_name;
    private Boolean copyright;

    public BaseFile() {
    }

    public BaseFile(Long id) {
        this.id = id;
    }

    public BaseFile(Long id, String path, String type, String name, Boolean selected, Boolean isdirectory, String size, java.util.Date time, String parent_folder_name, Boolean copyright) {
        this.id = id;
        this.path = path;
        this.type = type;
        this.name = name;
        this.selected = selected;
        this.isdirectory = isdirectory;
        this.size = size;
        this.time = time;
        this.parent_folder_name = parent_folder_name;
        this.copyright = copyright;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getSelected() {
        return selected;
    }

    public void setSelected(Boolean selected) {
        this.selected = selected;
    }

    public Boolean getIsdirectory() {
        return isdirectory;
    }

    public void setIsdirectory(Boolean isdirectory) {
        this.isdirectory = isdirectory;
    }

    public String getSize() {
        return size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public String getParent_folder_name() {
        return parent_folder_name;
    }

    public void setParent_folder_name(String parent_folder_name) {
        this.parent_folder_name = parent_folder_name;
    }

    public Boolean getCopyright() {
        return copyright;
    }

    public void setCopyright(Boolean copyright) {
        this.copyright = copyright;
    }

}
