package xy.media.oneplayer.data.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "VIDEO_GROUP_ENCRYPT".
 */
public class VideoGroupEncrypt {

    private Long id;
    private Boolean state;
    private String key;

    public VideoGroupEncrypt() {
    }

    public VideoGroupEncrypt(Long id) {
        this.id = id;
    }

    public VideoGroupEncrypt(Long id, Boolean state, String key) {
        this.id = id;
        this.state = state;
        this.key = key;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getState() {
        return state;
    }

    public void setState(Boolean state) {
        this.state = state;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

}
