package xy.media.oneplayer.data.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "VIDEO_POSITION".
 */
public class VideoPosition {

    private String path;
    private Integer position;
    private String tag;
    private Long group_id;

    public VideoPosition() {
    }

    public VideoPosition(String path) {
        this.path = path;
    }

    public VideoPosition(String path, Integer position, String tag, Long group_id) {
        this.path = path;
        this.position = position;
        this.tag = tag;
        this.group_id = group_id;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public Long getGroup_id() {
        return group_id;
    }

    public void setGroup_id(Long group_id) {
        this.group_id = group_id;
    }

}
